== NixOS on MBP

This is a repo that will house notes and scripts related to getting
NixOS running on a newer generation (late 2013+) MacBook Pro laptop
(Retina).

=== Prerequisites

Get comfortable with the Nix package manager on OSX first.

To do that you should install Nix and set it up on Yosemite to work
somewhat reasonably:

* link:bin/install-nix[] - install Nix from scratch
* link:bin/install-nixpkgs-yosemite[] - Setup the Nix installation on OSX
  to use the correct nixpkgs git remote and binary cache.

These scripts I wrote while trying to automate it myself, but probably
aren't great. Bug reports and patches welcomed. :)

=== Preparing Installation Media

Contrary to other reports on the internet (in the wild) you do not need
to prerpare your bootable USB installer on another Linux distro.

*You should be using 16.03 or 16.09 images at this point!*

As of 2016-09-09 here are the latest `nixos` image download locations:

* link:http://nixos.org/releases/nixos/16.03/nixos-16.03.1287.6ac7ffd/[16.03]
* link:http://nixos.org/releases/nixos/16.09/nixos-16.09beta172.e3bdf6b/[16.09beta]


[NOTICE]
====
For NixOS 14.12 and below:

I wrote the script link:bin/prepare-boot-drive-from-iso[] which could
use some more testing by others (please file bugs if you come across
them).

Link to original Gist is here: https://gist.github.com/mbbx6spp/61ab23d390483673c1b4
====

For NixOS 15.x and above you can just `dd` the ISO image downloaded
from the NixOS Download page.

The command I used on my NixOS box was the following, though on OSX you should
be able to use `/dev/disk2` or similar after unmounting the USB drive in OSX.

[source,bash]
----
sudo dd bs=4M if=path/to/nixos-minimal-15.09.431.52a881-x86_64-linux.iso of=/dev/sdc
----

=== Before Installing

You will need to resize your OSX partition. I resized mine to 50Gb. I did this
booting into the OSX Recovery partition and using the Disk Utility from there.

You cannot resize the current root partition thus why you need to do this :)

Leave the rest as empty.

=== Stage1 Installer Workaround

Yeah, I know, we need a workaround already. On 14.12 installer you will
likely encounter a problem with the device detected as the installer (i.e.
it will not).

Basically it will choose `/dev/sdc` if it is already mounted as `/dev/sdb`
or vice versa. And then inevitable fail.

Anyway, to get moving on this here is what I did:

[source]
----
Choose interactive shell to fix "/dev/sdc: No medium found" errors in stage 1.
Then the fix is the following:

* find proper device by `dmesg | grep 'logical blocks'` to find device for
  your USB drive. Say it is `/dev/sdb`.
* determine which partition on the device to mount by running `fdisk` and
  inspecting the partitions.
* Now mount it at /mnt-root/iso: `mount /dev/sdb1 /mnt-root/iso`.
----

Now `exit` the interactive shell in stage1 to proceed to stage2 loading.

=== Preparing Partitions in Stage2

If you are unsure on how to configure your partitions consult the `man gdisk`.
I suggest the following basic setup (this is what I did):

[source]
----
$ sudo gdisk -l /dev/sda

GPT fdisk (gdisk) version 0.8.8

Partition table scan:
  MBR: protective
  BSD: not present
  APM: not present
  GPT: present

Found valid GPT with protective MBR; using GPT.
Disk /dev/sda: 490234752 sectors, 233.8 GiB
Logical sector size: 512 bytes
Disk identifier (GUID): XXXXXXXXXXXXXXXXXXXXXXXX
Partition table holds up to 128 entries
First usable sector is 34, last usable sector is 490234718
Partitions will be aligned on 8-sector boundaries
Total free space is 6 sectors (3.0 KiB)

Number  Start (sector)    End (sector)  Size       Code  Name
   1              40          409639   200.0 MiB   EF00  EFI System Partition
   2          409640        98957655   47.0 GiB    AF05  Customer
   3        XXXXXXXX       XXXXXXXXX   620.0 MiB   AB00  Recovery HD
   4       XXXXXXXXX       XXXXXXXXX   170.0 GiB   8300  nixosroot
   5       XXXXXXXXX       XXXXXXXXX   16.0 GiB    8200  nixosswap
----

I did this with the following commands after stage2 loaded in the NixOS
installer:

[source,shell]
----
# mkfs.ext4 -L nixosroot /dev/sda4
# mkswap -L nixosswap /dev/sda5
----

If you do not already have a `vfat` filesystem for boot images you will need
to run the following command (I didn't need to do this):

[source,shell]
----
# mkfs.vfat /dev/sda1
----

Now we need to mount the new or existing filesystems:

----
# mount /dev/sda4 /mnt
# mkdir /mnt/boot
# mount /dev/sda1 /mnt/boot
# swapon /dev/disk/by-label/nixosswap
----

*Make sure you mount `/dev/sda1` under `/mnt/boot`.*

After that run: `nixos-generate-config --root /mnt`

After this you may want to modify the `configuration.nix` to include gummiboot.

Then run: `nixos-install`

=== Configuration Post-Install

My `/etc/nixos/configuration.nix` for the MBP can be found at
link:etc/nixos/configuration.nix[].

Some parts of note that are required for the MBP are:

==== Boot Options

Use gummiboot. I got gummiboot working straight away.

[source,nix]
----
{
  # Other stuff up here....

  boot.loader.grub.enable = false;
  boot.loader.gummiboot.enable = true;
  # I lowered this timeout because 4 seconds is too long for me
  boot.loader.gummiboot.timeout = 2;
  # Whether or not the installation process should modify EFI boot variables
  boot.loader.efi.canTouchEfiVariables = true;
  # If you rely on a dirty /tmp dir you are doing it wrong. Your laptop will
  # never be cattle.
  boot.cleanTmpDir = true;
  # This gets your audio output and input (mic) working
  boot.extraModprobeConfig = ''
    options libata.force=noncq
    options resume=/dev/sda5
    options snd_hda_intel index=0 model=intel-mac-auto id=PCH
    options snd_hda_intel index=1 model=intel-mac-auto id=HDMI
    options snd_hda_intel model=mbp101
    options hid_apple fnmode=2
  '';
  # because we are using the EFI mount for boot, which is small (tiny actually)
  # I switched these to false.
  boot.loader.generationsDir.enable = false;
  boot.loader.generationsDir.copyKernels = false;

  # other stuff down here
}
----

==== Tidbit: Audio

If you use xmonad and you want to attach your Fn keys to the appropriate audio
behaviors you are accustomed to on OSX/Darwin then you can
link:https://github.com/mbbx6spp/.home/blob/lookie/dotfiles/xmonad/xmonad.hs#L110-131[take a look at my `xmonad.hs` file].

For those just interested in the raw commands here they are below:

[source,shell]
----
$ amixer -q set Master toggle # mute/unmute
$ amixer -q set Master 5%- # decrease volume by 5%
$ amixer -q set Master 5%+ # increase volume by 5%
----

==== Tidbit: Brightness / Visual Tempurature

Some of you may be familiar with OSX apps that changes your brightness and
screen tone based on the time of day.

On Linux the best one I could find was redshift which is configurable in
NixOS via the link:https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/x11/redshift.nix[builtin module].

Here is an excerpt from my latest `/etc/nixos/configuration.nix` file for
redshift configs:

[source,javascript]
----
  services.redshift.enable = true;
  services.redshift.brightness.day = "0.8";
  services.redshift.brightness.night = "0.4";
  services.redshift.latitude = "0.0000";
  services.redshift.longitude = "0.0000";
----

For the raw commands to use to increase or decrease brightness see below:

[source,shell]
----
$ cat /sys/class/backlight/acpi_video0/brightness # echos current brightness level
10
$ cat /sys/class/backlight/acpi_video0/max_brightness # echos max brightness level
100
$ echo 25 | sudo tee /sys/class/backlight/acpi_video0/brightness # sets brightness to 25/100
$ cat /sys/class/backlight/acpi_video0/brightness
25
----

HTH!
